### ISSUE TITLE
Release 1.1.0?

### ISSUE THREAD

**Issue by jamesarosen** [splitio/vercel-integration-utils#17]
The `package.json` on the `main` branch [has](https://github.com/splitio/vercel-integration-utils/blob/61f0fb2b9726d35196c5f5f0d1c44bbf990dd1dd/package.json#L3)

```js
"version": "1.1.0"
```

but the latest version released to npm is 1.0.1. The [diff](https://github.com/splitio/vercel-integration-utils/compare/268d3fb6256a80a265ba50acdfb34261c3cbca46...61f0fb2b9726d35196c5f5f0d1c44bbf990dd1dd) is substantial.

**Comment by EmilianoSanchez** [comment]
Hi @jamesarosen  
Thank you so much for raising this issue. The publishing step was definitely missed in the last release. I will fix it ASAP, and then I will take a look into your other concerns.

**Comment by EmilianoSanchez** [comment]
Closing the issue now. Version 1.1.0 was released. And a new one, v1.1.1, with dependency bumps for security vulnerability fixes, was released too.
